# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PIQAG\PyGIT\PIQGUAG\exercise_8\plugin_folder\mcdt_script\csv_clicked_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CSV_Dialog(object):
    def setupUi(self, CSV_Dialog):
        CSV_Dialog.setObjectName("CSV_Dialog")
        CSV_Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(CSV_Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(CSV_Dialog)
        self.buttonBox.accepted.connect(CSV_Dialog.accept)
        self.buttonBox.rejected.connect(CSV_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CSV_Dialog)

    def retranslateUi(self, CSV_Dialog):
        _translate = QtCore.QCoreApplication.translate
        CSV_Dialog.setWindowTitle(_translate("CSV_Dialog", "Dialog"))
