# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PIQAG\PyGIT\PIQGUAG\exercise_8\plugin_folder\mcdt_script\export_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Export_Dialog(object):
    def setupUi(self, Export_Dialog):
        Export_Dialog.setObjectName("Export_Dialog")
        Export_Dialog.resize(400, 186)
        self.ok_quit_box = QtWidgets.QDialogButtonBox(Export_Dialog)
        self.ok_quit_box.setGeometry(QtCore.QRect(50, 150, 341, 32))
        self.ok_quit_box.setOrientation(QtCore.Qt.Horizontal)
        self.ok_quit_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ok_quit_box.setObjectName("ok_quit_box")
        self.label = QtWidgets.QLabel(Export_Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Export_Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 311, 16))
        self.label_2.setObjectName("label_2")
        self.output_path_lineEdit = QtWidgets.QLineEdit(Export_Dialog)
        self.output_path_lineEdit.setGeometry(QtCore.QRect(20, 120, 271, 16))
        self.output_path_lineEdit.setObjectName("output_path_lineEdit")
        self.output_pushButton = QtWidgets.QPushButton(Export_Dialog)
        self.output_pushButton.setGeometry(QtCore.QRect(300, 120, 31, 16))
        self.output_pushButton.setObjectName("output_pushButton")
        self.exportPDF_button = QtWidgets.QToolButton(Export_Dialog)
        self.exportPDF_button.setGeometry(QtCore.QRect(20, 50, 171, 19))
        self.exportPDF_button.setObjectName("exportPDF_button")
        self.exportCSV_button = QtWidgets.QToolButton(Export_Dialog)
        self.exportCSV_button.setGeometry(QtCore.QRect(200, 50, 171, 19))
        self.exportCSV_button.setObjectName("exportCSV_button")

        self.retranslateUi(Export_Dialog)
        self.ok_quit_box.accepted.connect(Export_Dialog.accept)
        self.ok_quit_box.rejected.connect(Export_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Export_Dialog)

    def retranslateUi(self, Export_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Export_Dialog.setWindowTitle(_translate("Export_Dialog", "Dialog"))
        self.label.setText(_translate("Export_Dialog", "Export"))
        self.label_2.setText(_translate("Export_Dialog", "Please enter the outputpath of the file:"))
        self.output_pushButton.setText(_translate("Export_Dialog", "..."))
        self.exportPDF_button.setText(_translate("Export_Dialog", "Export as PDF"))
        self.exportCSV_button.setText(_translate("Export_Dialog", "Export as CSV"))
        
    
