# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PIQAG\PyGIT\PIQGUAG\exercise_8\plugin_folder\mcdt_script\single_district_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_single_district_Dialog(object):
    def setupUi(self, single_district_Dialog):
        single_district_Dialog.setObjectName("single_district_Dialog")
        single_district_Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(single_district_Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(single_district_Dialog)
        self.buttonBox.accepted.connect(single_district_Dialog.accept)
        self.buttonBox.rejected.connect(single_district_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(single_district_Dialog)

    def retranslateUi(self, single_district_Dialog):
        _translate = QtCore.QCoreApplication.translate
        single_district_Dialog.setWindowTitle(_translate("single_district_Dialog", "Dialog"))
